import { Month, Category, Expense } from '../data/budgetStore';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export function formatMonthLabel(mKey: string): string {
  const [year, month] = mKey.split('-');
  const idx = parseInt(month, 10) - 1;
  const name = idx >= 0 && idx < 12 ? MONTH_NAMES[idx] : month;
  return `${name} ${year}`;
}

function getCategoryName(categories: Category[], categoryId: string): string {
  const category = categories.find(c => c.id === categoryId);
  return category?.name || 'Unknown';
}

function sortExpenses(expenses: Expense[]): Expense[] {
  return [...expenses].sort(
    (a, b) => new Date(b.dateIso).getTime() - new Date(a.dateIso).getTime()
  );
}

// ─── PDF ───

export function generatePdfHtml(
  month: Month,
  categories: Category[],
  formatAmount: (amount: number) => string,
  monthLabel: string
): string {
  const sorted = sortExpenses(month.expenses);
  const totalSpent = sorted.reduce((sum, e) => sum + e.amount, 0);
  const remaining = month.income - totalSpent;

 
  const groups: { date: string; items: Expense[] }[] = [];
  for (const expense of sorted) {
    const last = groups[groups.length - 1];
    if (last && last.date === expense.dateIso) {
      last.items.push(expense);
    } else {
      groups.push({ date: expense.dateIso, items: [expense] });
    }
  }

  const transactionRows = groups
    .map((group) => {
      const dateHeader = `<tr><td colspan="4" style="padding:12px 8px 4px;font-weight:600;color:#666;border-bottom:1px solid #eee;">${group.date}</td></tr>`;
      const items = group.items
        .map(
          (e) =>
            `<tr>
              <td style="padding:6px 8px;">${e.dateIso}</td>
              <td style="padding:6px 8px;">${getCategoryName(categories, e.categoryId)}</td>
              <td style="padding:6px 8px;">${e.note || '-'}</td>
              <td style="padding:6px 8px;text-align:right;color:#DC2626;">-${formatAmount(e.amount)}</td>
            </tr>`
        )
        .join('');
      return dateHeader + items;
    })
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #1a1a2e; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
    .summary { display: flex; gap: 24px; margin-bottom: 24px; }
    .summary-item { padding: 12px 16px; border: 1px solid #e5e7eb; border-radius: 8px; flex: 1; text-align: center; }
    .summary-label { font-size: 12px; color: #666; }
    .summary-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
    .green { color: #10B981; }
    .red { color: #DC2626; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 8px; border-bottom: 2px solid #222; font-size: 13px; }
    th:last-child { text-align: right; }
    tr:last-child td { border-bottom: none; }
    .footer { margin-top: 32px; font-size: 11px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <h1>CashFlow Report</h1>
  <div class="subtitle">${monthLabel}</div>

  <div class="summary">
    <div class="summary-item">
      <div class="summary-label">Income</div>
      <div class="summary-value green">${formatAmount(month.income)}</div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Total Spent</div>
      <div class="summary-value red">${formatAmount(totalSpent)}</div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Remaining</div>
      <div class="summary-value">${formatAmount(remaining)}</div>
    </div>
  </div>

  ${sorted.length === 0
    ? '<p style="color:#666;">No transactions this month.</p>'
    : `<table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Category</th>
            <th>Note</th>
            <th style="text-align:right;">Amount</th>
          </tr>
        </thead>
        <tbody>${transactionRows}</tbody>
      </table>`
  }

  <div class="footer">Generated by CashFlow</div>
</body>
</html>`;
}

// ─── CSV ───

export function generateCsvContent(
  month: Month,
  categories: Category[],
  monthLabel: string
): string {
  const sorted = sortExpenses(month.expenses);
  const totalSpent = sorted.reduce((sum, e) => sum + e.amount, 0);
  const remaining = month.income - totalSpent;

  const header = 'Date,Category,Note,Amount';
  const rows = sorted.map((e) => {
    const note = (e.note || '').replace(/"/g, '""');
    return `${e.dateIso},"${getCategoryName(categories, e.categoryId)}","${note}",-${e.amount.toFixed(2)}`;
  });

  const summary = [
    '',
    `Summary for ${monthLabel}`,
    `Income,${month.income.toFixed(2)}`,
    `Total Spent,${totalSpent.toFixed(2)}`,
    `Remaining,${remaining.toFixed(2)}`,
  ];

  return [header, ...rows, ...summary].join('\n');
}

// ─── Yearly PDF ───

export function generateYearlyPdfHtml(
  months: Record<string, Month>,
  formatAmount: (amount: number) => string,
  year: string
): string {
  const sortedKeys = Object.keys(months).sort();
  let totalIncome = 0;
  let totalSpent = 0;
  let allExpenses: (Expense & { monthLabel: string; categoryName: string })[] = [];

  // Collect all categories across months for name lookups
  const allCategories: Category[] = [];
  for (const mKey of sortedKeys) {
    const month = months[mKey];
    for (const cat of month.categories) {
      if (!allCategories.find(c => c.id === cat.id)) allCategories.push(cat);
    }
  }

  // Build month-by-month summary rows and collect expenses
  const monthRows = sortedKeys.map((mKey) => {
    const month = months[mKey];
    const spent = month.expenses.reduce((sum, e) => sum + e.amount, 0);
    const remaining = month.income - spent;
    totalIncome += month.income;
    totalSpent += spent;

    for (const e of month.expenses) {
      allExpenses.push({
        ...e,
        monthLabel: formatMonthLabel(mKey),
        categoryName: getCategoryName(allCategories, e.categoryId),
      });
    }

    return `<tr>
      <td style="padding:6px 8px;">${formatMonthLabel(mKey)}</td>
      <td style="padding:6px 8px;color:#10B981;">${formatAmount(month.income)}</td>
      <td style="padding:6px 8px;color:#DC2626;">${formatAmount(spent)}</td>
      <td style="padding:6px 8px;">${formatAmount(remaining)}</td>
      <td style="padding:6px 8px;text-align:right;">${month.expenses.length}</td>
    </tr>`;
  }).join('');

  const totalRemaining = totalIncome - totalSpent;

  // Sort all expenses by date
  allExpenses.sort((a, b) => new Date(b.dateIso).getTime() - new Date(a.dateIso).getTime());

  const transactionRows = allExpenses.map((e) =>
    `<tr>
      <td style="padding:4px 8px;">${e.dateIso}</td>
      <td style="padding:4px 8px;">${e.categoryName}</td>
      <td style="padding:4px 8px;">${e.note || '-'}</td>
      <td style="padding:4px 8px;text-align:right;color:#DC2626;">-${formatAmount(e.amount)}</td>
    </tr>`
  ).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #1a1a2e; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 32px; margin-bottom: 12px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
    .summary { display: flex; gap: 24px; margin-bottom: 24px; }
    .summary-item { padding: 12px 16px; border: 1px solid #e5e7eb; border-radius: 8px; flex: 1; text-align: center; }
    .summary-label { font-size: 12px; color: #666; }
    .summary-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
    .green { color: #10B981; }
    .red { color: #DC2626; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { text-align: left; padding: 8px; border-bottom: 2px solid #222; font-size: 13px; }
    th:last-child { text-align: right; }
    tr:last-child td { border-bottom: none; }
    .footer { margin-top: 32px; font-size: 11px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <h1>CashFlow Yearly Report</h1>
  <div class="subtitle">${year}</div>

  <div class="summary">
    <div class="summary-item">
      <div class="summary-label">Total Income</div>
      <div class="summary-value green">${formatAmount(totalIncome)}</div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Total Spent</div>
      <div class="summary-value red">${formatAmount(totalSpent)}</div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Net</div>
      <div class="summary-value">${formatAmount(totalRemaining)}</div>
    </div>
  </div>

  <h2>Monthly Breakdown</h2>
  <table>
    <thead>
      <tr>
        <th>Month</th>
        <th>Income</th>
        <th>Spent</th>
        <th>Remaining</th>
        <th style="text-align:right;">Transactions</th>
      </tr>
    </thead>
    <tbody>${monthRows}</tbody>
  </table>

  ${allExpenses.length === 0
    ? '<p style="color:#666;">No transactions this year.</p>'
    : `<h2>All Transactions</h2>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Category</th>
            <th>Note</th>
            <th style="text-align:right;">Amount</th>
          </tr>
        </thead>
        <tbody>${transactionRows}</tbody>
      </table>`
  }

  <div class="footer">Generated by CashFlow</div>
</body>
</html>`;
}

// ─── Yearly CSV ───

export function generateYearlyCsvContent(
  months: Record<string, Month>,
  year: string
): string {
  const sortedKeys = Object.keys(months).sort();
  let totalIncome = 0;
  let totalSpent = 0;

  // Collect all categories for name lookups
  const allCategories: Category[] = [];
  for (const mKey of sortedKeys) {
    for (const cat of months[mKey].categories) {
      if (!allCategories.find(c => c.id === cat.id)) allCategories.push(cat);
    }
  }

  // Collect all expenses
  const allExpenses: Expense[] = [];
  const monthSummaries: string[] = [];

  for (const mKey of sortedKeys) {
    const month = months[mKey];
    const spent = month.expenses.reduce((sum, e) => sum + e.amount, 0);
    totalIncome += month.income;
    totalSpent += spent;
    monthSummaries.push(`${formatMonthLabel(mKey)},${month.income.toFixed(2)},${spent.toFixed(2)},${(month.income - spent).toFixed(2)}`);
    allExpenses.push(...month.expenses);
  }

  // Sort expenses by date descending
  allExpenses.sort((a, b) => new Date(b.dateIso).getTime() - new Date(a.dateIso).getTime());

  const header = 'Date,Category,Note,Amount';
  const rows = allExpenses.map((e) => {
    const note = (e.note || '').replace(/"/g, '""');
    return `${e.dateIso},"${getCategoryName(allCategories, e.categoryId)}","${note}",-${e.amount.toFixed(2)}`;
  });

  const totalRemaining = totalIncome - totalSpent;
  const summary = [
    '',
    `Yearly Summary for ${year}`,
    'Month,Income,Spent,Remaining',
    ...monthSummaries,
    '',
    `Total Income,${totalIncome.toFixed(2)}`,
    `Total Spent,${totalSpent.toFixed(2)}`,
    `Net,${totalRemaining.toFixed(2)}`,
  ];

  return [header, ...rows, ...summary].join('\n');
}
